### ISSUE TITLE
Feature request: "Stop spawning"/"Start Spawning" function

### ISSUE THREAD

**Issue by thebgpikester** [birgersp/dcs-autogft#101]
The reason I'd like to see this (or something to the same effect) is to perhaps use more complex Scripting triggers to control when a base spawns and when it stops. Scenarios include, arrival of reinforcements, start of advance (start), base being over run, airfield/warehouse or objective being captured(stop)

Currently we can have a finite limit or a rate of respawning, but not an absolute start/stop that I know of.

It would be a step towards the goal of warehousing, simply triggering things.

**Comment by birgersp** [comment]
Stopping reinforcements (including respawns) can be done with [`stopReinforcing`](https://birgersp.github.io/dcs-autogft/TaskForce.html##(TaskForce).stopReinforcing)

A procedure how to stop the task force on some event is explained here:
https://forums.eagle.ru/showthread.php?p=3010044#87
