### ISSUE TITLE
Units not moving from base zone

### ISSUE THREAD

**Issue by Aarnoman** [birgersp/dcs-autogft#122]
DCS version: Stable (2.5.6.59625 )

Steps to reproduce: 
1) Start example mission included with autogft in 1.18.
2) Enter F10 map.
3) Speed up time (Ctrl+Z), observe most units not moving from base.
4) Observe one of the Humvees still able to move through multiple units. 

Likely related to bug #121, but now affects stable as well (Stable was updated on 26/12/2020). Additionally, one unit is able to cycle through multiple waypoints.

**Comment by birgersp** [comment]
Thanks! Not all of these units are supposed to start moving.

Many of these units are used for "staging". That means they are idle until they are needed in battle.

If you do spot a bug, please narrow it down more. Exactly which units are affected? In which zone are they?
