### ISSUE TITLE
Add ability to use intermidiate zones for units to go through when advancing

### ISSUE THREAD

**Issue by birgersp** [birgersp/dcs-autogft#55]
(Related to #52)

**Comment by thebgpikester** [comment]
1. Avoids areas with towns, bridges, hills and undesirable and expensive route finding
2. Deals with the issue of where the unit should STAY and th eway it should get there to its ultimate destination - the reaosn that this could be an issue is that we could see AI constantly chase its tails...ie it sees a vacant zone, runs to it, the other side does the same. Ad infinitum.
3. It's somewhat realistic to set a Group one objective in a general military sense. The mission will always have a goal in mind from the begining that's unlikely to vastly change in the same session.

**Comment by birgersp** [comment]
Will be covered in #20
