### ISSUE TITLE
Add alternative to specifying units

### ISSUE THREAD

**Issue by birgersp** [birgersp/dcs-autogft#57]
If task force has no unit specifications, use existing groups in the base zones as unit specifications

**Comment by thebgpikester** [comment]
Some options for this

1. A default Task Force template. All groups not explicitly refrenced in the TF lua will adopt the speed, travel type, skill and objective lists of the default template.

2. We have a hard coded fall back if none exists? eg, NO OBJECTIVE (ie don't move) skill avg, speed 11, dont use roads.

3. Use a template group as implied in the first comment: ie one group is defined as LATE ACTIVATION and provides the source of allsettings...ie a destination, a skill, and formation etc.

4. ???

**Comment by thebgpikester** [comment]
Due to #58, #59, #60 it looks like the method for taking a previously unknown unit and giving it the same objectives between restarting the mission or the script would be to associate the name of the group with the task it has, both when spawned and when initially placed. Wil break this out as another issue.

**Comment by birgersp** [comment]
Interesting ideas, it would probably be very useful for new users to create working task forces with simply:

```
autogft_TaskForce:new()
  :setCountry(country.id.USA)
  :addBaseZone("Base1")
  :addBaseZone("Base2")
  :addTargetZone("Combat1")
  :addTargetZone("Combat2")
  :addTargetZone("Combat3")
```

And then a default unit specification is automatically. Do you have some suggestion for default unit specifications?

**Comment by thebgpikester** [comment]
Not really, random stuff is fine. The only thing I don't know that I shoudl know, to make that decision is the effect of using on road, where none exist on a unit not near a road. In which case off road default might be ideal. Skill avg, speed 11 seem fine.

**Comment by thebgpikester** [comment]
ANother question, woudl you prefer that every mission has at least ONE objective? can we enforce this?

**Comment by birgersp** [comment]
Every task force must have at least one objective, or the mission will throw an error ([take a look](https://github.com/birgersp/dcs-autogft/blob/1.5/autogft/taskforce.lua#L259)).

I'm working on a function to "add groups" and "add units" automatically. With this function, the mission designer can put some groups in the base zone and the task force will assume that the units put there define which groups and units the task force shall consist of.

For instance, put a group of 4 M-1 Abrams and 3 LAV-25s in the base zone, don't specify any units for the task force but specify base and target zones as normal. Then (once on mission start), the task force will assume that you want the task force to consist of the units you've put in the base zones. So on respawn you'll get two new groups: 4 M-1 Abrams and 3 LAV-25s.

Then this is all you need to put in the mission script (example.lua):
```
autogft_TaskForce:new()
  :addBaseZone("SPAWN1")
  :addControlZone("Combat1")
  :setRespawnTimer(600)
```

- Add function `autoInitializeUnits`
