### ISSUE TITLE
Units go offroad when advancing to zones even though useRoads is set to true

### ISSUE THREAD

**Issue by birgersp** [birgersp/dcs-autogft#71]
- Make a custom implementation of waypoint assignment

**Comment by 457Stonehouse** [comment]
Also may be applicable to the bridges issue. See https://forums.eagle.ru/showthread.php?t=120195 and https://forums.eagle.ru/showthread.php?t=120675

**Comment by birgersp** [comment]
Fixed in 8bee291951044c95e3a4a7282af0d6b986420a13 (version 1.8)
